version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13.5-alpine
        environment:
          GOFLAGS: -mod=vendor
    steps:
      - checkout
      - run: go test -v ./...
  lint:
    docker:
    - image: golangci/golangci-lint:1.22.2-alpine
    steps:
      - checkout
      - run: golangci-lint run ./...
workflows:
  version: 2
  tests:
    jobs:
      - test
      - lint
